name: cherrypick workflow


on: push

jobs:
  build-n-publish:
    name: Build and Publish CherryPick
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          pip install -r requirements_dev.txt
          pip install setuptools wheel twine
          pip install tox
          pip install pytest
          
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python3 -m
          build
          --sdist
          --wheel
          --outdir dist/
          
      - name: Running Tests
        run: |
          tox

      - name: Publish distribution to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
#         env:
#           TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#           TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#         run: |
#           python setup.py sdist bdist_wheel
#           twine upload dist/*
